name: NanoTekSpice

env:
  EXECUTABLES: "nanotekspice"
  ARGS: ""
  MIRROR_URL: "git@github.com:EpitechPromo2028/B-OOP-400-LIL-4-1-tekspice-mathis.bukowski.git"
  MIRROR_NAME: "EpitechPromo2028/B-OOP-400-LIL-4-1-tekspice-mathis.bukowski"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/**'

jobs:
  check_program_compilation:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Create Build Directory"
        run: mkdir -p build

      - name: "Compile the Program with CMake and Make"
        run: |
          cd build
          cmake ..
          make
        timeout-minutes: 5

      - name: "Verify Executable Permissions and Presence"
        env:
          EXECUTABLES: "$EXECUTABLES"
        run: |
          IFS=','; for executable in $EXECUTABLES; do
            if [ -f "build/$executable" ] && [ -x "build/$executable" ]; then
                echo "$executable exists and is executable."
            else
                echo "$executable does not exist or is not executable."
                exit 1
            fi
          done

      - name: "Test Executable Program Launch"
        env:
          ARGS: "$ARGS"
        run: |
          for executable in $EXECUTABLES; do
            echo "Testing execution of $executable with arguments: $ARGS"
            ./build/$executable $ARGS || exit 1
          done

  push_to_mirror:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: check_program_compilation
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Push to Mirror Repository"
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
